name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Compilar APK Android
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependencias del Proyecto
        run: |
          npm ci
          
      - name: Generar Código de Producción (Vite)
        run: |
          npm run build
 
      - name: Verificar Archivos Pre-compilados
        run: |
          ls -R android/app/src/main/assets
 
      - name: Configurar Gradle y Java 17
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: '17'
 
      - name: Compilar APK (Debug)
        working-directory: ./android
        run: |
          sed -i 's/\r$//' ./gradlew
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Subir Registros de Error (En caso de fallo)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-build-reports
          path: |
            android/app/build/reports/
            android/app/build/test-results/

      - name: Subir APK Generado
        uses: actions/upload-artifact@v4
        with:
          name: AniFlix-Android-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
